databases:
  - name: payjic
    ipAllowList: []
    plan: free
    user: payjic

services:
  - type: web
    plan: free
    name: payjic
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: payjic
          property: connectionString
      